/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.alejandrove.cuidarpokemon.frontend;

import com.alejandrove.cuidarpokemon.backend.Jugador;
import com.alejandrove.cuidarpokemon.backend.Log;
import com.alejandrove.cuidarpokemon.backend.Mascota;
import com.alejandrove.cuidarpokemon.backend.helpers.HelperClass;
import com.alejandrove.cuidarpokemon.backend.helpers.LogTypes;

import java.util.Arrays;

import javax.swing.JFrame;

/**
 *
 * @author aleja
 */
public class ReportesFrame extends javax.swing.JFrame {

    JFrame parent;
    Log[] logs;
    Log[] realLogs;
    String[] logsString;

    /**
     * Creates new form ReportesFrame
     */
    public ReportesFrame(JFrame parent, Log[] logs) {
        this.parent = parent;
        this.logs = logs;
        initComponents();
        menorMayorButton.setVisible(false);
        mayorMenorButton.setVisible(false);
        rellenarLogsFecha();
    }

    public void rellenarLogsFecha() {
        realLogs = new Log[HelperClass.getTotalLogs(logs)];
        logsString = new String[realLogs.length];
        for (int i = 0; i < realLogs.length; i++) {
            realLogs[i] = logs[i];
            logsString[i] = realLogs[i].toString();
        }
        logsList.setListData(logsString);
    }

    public void rellenarTipo(String tipo) {
        String[] logsTipoString = Arrays
                .stream(Arrays.stream(realLogs).filter(log -> log.getTipo() == tipo).toArray(Log[]::new))
                .map(log -> log.toString()).toArray(String[]::new);
        logsList.setListData(logsTipoString);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tipoLogComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        logsList = new javax.swing.JList<>();
        jButton10 = new javax.swing.JButton();
        menorMayorButton = new javax.swing.JButton();
        mayorMenorButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        jLabel1.setText("Reportes");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel2.setText("Filtrar por:");

        tipoLogComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        tipoLogComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fecha", "Enfermedad", "Comida",
                "Paseo", "Nivel", "Muerte", "Nacimiento", "Limpieza" }));
        tipoLogComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoLogComboBoxActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(logsList);

        jButton10.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jButton10.setText("Regresar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        menorMayorButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        menorMayorButton.setText("menor a mayor");
        menorMayorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menorMayorButtonActionPerformed(evt);
            }
        });

        mayorMenorButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        mayorMenorButton.setText("mayor a menor");
        mayorMenorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mayorMenorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(30, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(menorMayorButton)
                                                        .addComponent(mayorMenorButton))
                                                .addGap(56, 56, 56)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(17, 17, 17)
                                                                .addComponent(jLabel1))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(tipoLogComboBox,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 106,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                        layout.createSequentialGroup()
                                                                .addComponent(jButton10)
                                                                .addContainerGap())
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                        layout.createSequentialGroup()
                                                                .addComponent(jScrollPane1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 568,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(30, 30, 30))))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(jLabel1)
                                                .addGap(36, 36, 36))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .addComponent(mayorMenorButton)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(menorMayorButton))
                                        .addComponent(tipoLogComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton10)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menorMayorButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_menorMayorButtonActionPerformed
        Log[] logsNivel = Arrays.stream(realLogs).filter(log -> log.getTipo() == LogTypes.nivel)
                .sorted(new OrdenarPorNivelMenorMayor()).toArray(Log[]::new);
        String[] logsNivelString = Arrays.stream(logsNivel).map(log -> log.toString()).toArray(String[]::new);
        logsList.setListData(logsNivelString);
    }// GEN-LAST:event_menorMayorButtonActionPerformed

    private void mayorMenorButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mayorMenorButtonActionPerformed
        Log[] logsNivel = Arrays.stream(realLogs).filter(log -> log.getTipo() == LogTypes.nivel)
                .sorted(new OrdenarPorNivelMayorMenor()).toArray(Log[]::new);
        String[] logsNivelString = Arrays.stream(logsNivel).map(log -> log.toString()).toArray(String[]::new);
        logsList.setListData(logsNivelString);
    }// GEN-LAST:event_mayorMenorButtonActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton10ActionPerformed
        this.setVisible(false);
        parent.setVisible(true);
        // TODO add your handling code here:
    }// GEN-LAST:event_jButton10ActionPerformed

    private void tipoLogComboBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tipoLogComboBoxActionPerformed
        int tipoElegido = tipoLogComboBox.getSelectedIndex();
        menorMayorButton.setVisible(false);
        mayorMenorButton.setVisible(false);
        switch (tipoElegido) {
            case 0:
                rellenarLogsFecha();
                break;
            case 1:
                rellenarTipo(LogTypes.enfermedad);
                break;
            case 2:
                rellenarTipo(LogTypes.comida);
                break;
            case 3:
                rellenarTipo(LogTypes.paseo);
                break;
            case 4:
                rellenarTipo(LogTypes.nivel);
                menorMayorButton.setVisible(true);
                mayorMenorButton.setVisible(true);
                break;
            case 5:
                rellenarTipo(LogTypes.muerte);
                break;
            case 6:
                rellenarTipo(LogTypes.nacimiento);
                break;
            case 7:
                rellenarTipo(LogTypes.limpieza);
                break;
            default:
                break;
        }
    }// GEN-LAST:event_tipoLogComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> logsList;
    private javax.swing.JButton mayorMenorButton;
    private javax.swing.JButton menorMayorButton;
    private javax.swing.JComboBox<String> tipoLogComboBox;
    // End of variables declaration//GEN-END:variables
}
