/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.alejandrove.cuidarpokemon.frontend.mascota;

import com.alejandrove.cuidarpokemon.backend.MotorJuego;
import com.alejandrove.cuidarpokemon.backend.Mascota;
import com.alejandrove.cuidarpokemon.backend.helpers.EstadosTypes;
import com.alejandrove.cuidarpokemon.backend.tienda.medicina.Medicina;
import java.util.Arrays;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author aleja
 */
public class CurarFrame extends javax.swing.JFrame {

    JFrame parent;
    MotorJuego juego;
    Mascota mascota;
    Medicina[] medicinasJugador;

    /**
     * Creates new form CurarFrame
     */
    public CurarFrame(JFrame parent, MotorJuego juego, Mascota mascota) {
        this.parent = parent;
        this.juego = juego;
        this.mascota = mascota;
        initComponents();
        rellenarMedicinasJugador();
    }

    public void rellenarMedicinasJugador() {
        String[] medicinasJugadorString = new String[juego.jugador.getTotalMedicinas()];
        medicinasJugador = new Medicina[juego.jugador.getTotalMedicinas()];
        for (int i = 0; i < medicinasJugadorString.length; i++) {
            medicinasJugador[i] = juego.jugador.medicinas[i];
            medicinasJugadorString[i] = juego.jugador.medicinas[i].getNombre();
        }
        medicinasJugadorList.setListData(medicinasJugadorString);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        medicinasJugadorList = new javax.swing.JList<>();
        jButton10 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jButton1.setText("Curar con la medicina seleccionada");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        jLabel1.setText("Curar Pokemon");

        jScrollPane1.setViewportView(medicinasJugadorList);

        jButton10.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jButton10.setText("Regresar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel2.setText("Tienes las siguientes medicinas, ¿Con cuál deseas curar a tu pokemon?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(40, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout.createSequentialGroup()
                                                        .addComponent(jButton10)
                                                        .addContainerGap())
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout.createSequentialGroup()
                                                        .addComponent(jLabel2)
                                                        .addGap(25, 25, 25))))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(106, 106, 106)
                                                .addComponent(jLabel1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(126, 126, 126)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(117, 117, 117)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 248,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addGap(16, 16, 16)
                                .addComponent(jButton10)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton10ActionPerformed
        this.setVisible(false);
        parent.setVisible(true);
        // TODO add your handling code here:
    }// GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        if (mascota.getPeticionesCurar() > 0) {
            try {
                if (mascota.getEstado() != EstadosTypes.muerto) {

                    int indiceMedicinaSeleccionada = medicinasJugadorList.getLeadSelectionIndex();
                    Medicina medicinaAUsar = medicinasJugador[indiceMedicinaSeleccionada];
                    mascota.curar(medicinaAUsar);
                    juego.jugador.medicinas = Arrays.stream(juego.jugador.medicinas)
                            .filter(medicina -> !medicinaAUsar.equals(medicina))
                            .toArray(Medicina[]::new);
                    juego.jugador.disminuirMedicinas();
                    rellenarMedicinasJugador();
                    JOptionPane.showMessageDialog(this,
                            "La medicina " + medicinaAUsar.getNombre() + " se le dio al pokemon",
                            "Pokemon curar", JOptionPane.INFORMATION_MESSAGE);

                } else {
                    // TODO: Manejar esto como excepción
                    JOptionPane.showMessageDialog(this,
                            "No puedes realizar esta acción porque tu pokemon esta muerto :(, puedes revivirlo desde su ventana",
                            "Error al curar", JOptionPane.ERROR_MESSAGE);
                }
            } catch (ArrayIndexOutOfBoundsException e) {
                JOptionPane.showMessageDialog(this,
                        "No has seleccionado ninguna medicina, puedes comprar en la tienda",
                        "Error al curar", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "Tu mascota no necesita ser curada",
                    "Curar mascota", JOptionPane.INFORMATION_MESSAGE);
        }

    }// GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> medicinasJugadorList;
    // End of variables declaration//GEN-END:variables
}
