/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.alejandrove.cuidarpokemon.frontend.mascota;

import com.alejandrove.cuidarpokemon.backend.Mascota;
import com.alejandrove.cuidarpokemon.backend.MotorJuego;
import com.alejandrove.cuidarpokemon.backend.helpers.HelperClass;

import java.awt.Image;
import java.io.IOException;
import java.net.URL;

import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author aleja
 */
public class MascotasFrame extends javax.swing.JFrame {
        JFrame parent;
        MotorJuego juego;

        /**
         * Creates new form MascotasFrame
         */
        public MascotasFrame(JFrame parent, MotorJuego juego) {
                this.parent = parent;
                this.juego = juego;
                initComponents();
                setPokemonData(pokemonImageLabel1, pokemonTitleLabel1, pokemonPanel1, juego.jugador.mascotas[0]);
                setPokemonData(pokemonImageLabel2, pokemonTitleLabel2, pokemonPanel2, juego.jugador.mascotas[1]);
                setPokemonData(pokemonImageLabel3, pokemonTitleLabel3, pokemonPanel3, juego.jugador.mascotas[2]);
                setPokemonData(pokemonImageLabel4, pokemonTitleLabel4, pokemonPanel4, juego.jugador.mascotas[3]);
                setPokemonData(pokemonImageLabel5, pokemonTitleLabel5, pokemonPanel5, juego.jugador.mascotas[4]);
                setPokemonData(pokemonImageLabel6, pokemonTitleLabel6, pokemonPanel6, juego.jugador.mascotas[5]);
                setPokemonData(pokemonImageLabel7, pokemonTitleLabel7, pokemonPanel7, juego.jugador.mascotas[6]);
                setPokemonData(pokemonImageLabel8, pokemonTitleLabel8, pokemonPanel8, juego.jugador.mascotas[7]);
                setPokemonData(pokemonImageLabel9, pokemonTitleLabel9, pokemonPanel9, juego.jugador.mascotas[8]);
                setPokemonData(pokemonImageLabel10, pokemonTitleLabel10, pokemonPanel10, juego.jugador.mascotas[9]);
        }

        private void setPokemonData(JLabel image, JLabel title, JPanel panel, Mascota pokemon) {
                if (pokemon != null) {
                        panel.setBorder(BorderFactory.createTitledBorder(pokemon.getNombre()));
                        HelperClass.scaleImage(pokemon.getSprite(), image);
                        title.setText(pokemon.getApodo());
                }
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        imageContainerPanel = new javax.swing.JPanel();
        pokemonPanel1 = new javax.swing.JPanel();
        pokemonImageLabel1 = new javax.swing.JLabel();
        pokemonTitleLabel1 = new javax.swing.JLabel();
        pokemonPanel2 = new javax.swing.JPanel();
        pokemonImageLabel2 = new javax.swing.JLabel();
        pokemonTitleLabel2 = new javax.swing.JLabel();
        pokemonPanel3 = new javax.swing.JPanel();
        pokemonImageLabel3 = new javax.swing.JLabel();
        pokemonTitleLabel3 = new javax.swing.JLabel();
        pokemonPanel4 = new javax.swing.JPanel();
        pokemonImageLabel4 = new javax.swing.JLabel();
        pokemonTitleLabel4 = new javax.swing.JLabel();
        pokemonPanel5 = new javax.swing.JPanel();
        pokemonImageLabel5 = new javax.swing.JLabel();
        pokemonTitleLabel5 = new javax.swing.JLabel();
        pokemonPanel6 = new javax.swing.JPanel();
        pokemonImageLabel6 = new javax.swing.JLabel();
        pokemonTitleLabel6 = new javax.swing.JLabel();
        pokemonPanel7 = new javax.swing.JPanel();
        pokemonImageLabel7 = new javax.swing.JLabel();
        pokemonTitleLabel7 = new javax.swing.JLabel();
        pokemonPanel8 = new javax.swing.JPanel();
        pokemonImageLabel8 = new javax.swing.JLabel();
        pokemonTitleLabel8 = new javax.swing.JLabel();
        pokemonPanel9 = new javax.swing.JPanel();
        pokemonImageLabel9 = new javax.swing.JLabel();
        pokemonTitleLabel9 = new javax.swing.JLabel();
        pokemonPanel10 = new javax.swing.JPanel();
        pokemonImageLabel10 = new javax.swing.JLabel();
        pokemonTitleLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mascotas");

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        jLabel1.setText("Mascotas");

        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(555, 431));

        imageContainerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        imageContainerPanel.setAutoscrolls(true);
        imageContainerPanel.setPreferredSize(new java.awt.Dimension(555, 1191));

        pokemonPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Espacio vacío", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 14))); // NOI18N
        pokemonPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pokemonPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pokemonPanel1MouseClicked(evt);
            }
        });

        pokemonTitleLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pokemonPanel1Layout = new javax.swing.GroupLayout(pokemonPanel1);
        pokemonPanel1.setLayout(pokemonPanel1Layout);
        pokemonPanel1Layout.setHorizontalGroup(
            pokemonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pokemonPanel1Layout.createSequentialGroup()
                .addComponent(pokemonTitleLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pokemonPanel1Layout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addComponent(pokemonImageLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        pokemonPanel1Layout.setVerticalGroup(
            pokemonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pokemonPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pokemonTitleLabel1)
                .addGap(18, 18, 18)
                .addComponent(pokemonImageLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pokemonPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Espacio vacío", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 14))); // NOI18N
        pokemonPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pokemonPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pokemonPanel2MouseClicked(evt);
            }
        });

        pokemonTitleLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pokemonPanel2Layout = new javax.swing.GroupLayout(pokemonPanel2);
        pokemonPanel2.setLayout(pokemonPanel2Layout);
        pokemonPanel2Layout.setHorizontalGroup(
            pokemonPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pokemonPanel2Layout.createSequentialGroup()
                .addComponent(pokemonTitleLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pokemonPanel2Layout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addComponent(pokemonImageLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        pokemonPanel2Layout.setVerticalGroup(
            pokemonPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pokemonPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pokemonTitleLabel2)
                .addGap(18, 18, 18)
                .addComponent(pokemonImageLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pokemonPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Espacio vacío", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 14))); // NOI18N
        pokemonPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pokemonPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pokemonPanel3MouseClicked(evt);
            }
        });

        pokemonTitleLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pokemonPanel3Layout = new javax.swing.GroupLayout(pokemonPanel3);
        pokemonPanel3.setLayout(pokemonPanel3Layout);
        pokemonPanel3Layout.setHorizontalGroup(
            pokemonPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pokemonPanel3Layout.createSequentialGroup()
                .addComponent(pokemonTitleLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pokemonPanel3Layout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addComponent(pokemonImageLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        pokemonPanel3Layout.setVerticalGroup(
            pokemonPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pokemonPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pokemonTitleLabel3)
                .addGap(18, 18, 18)
                .addComponent(pokemonImageLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pokemonPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Espacio vacío", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 14))); // NOI18N
        pokemonPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pokemonPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pokemonPanel4MouseClicked(evt);
            }
        });

        pokemonTitleLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pokemonPanel4Layout = new javax.swing.GroupLayout(pokemonPanel4);
        pokemonPanel4.setLayout(pokemonPanel4Layout);
        pokemonPanel4Layout.setHorizontalGroup(
            pokemonPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pokemonPanel4Layout.createSequentialGroup()
                .addComponent(pokemonTitleLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pokemonPanel4Layout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addComponent(pokemonImageLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        pokemonPanel4Layout.setVerticalGroup(
            pokemonPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pokemonPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pokemonTitleLabel4)
                .addGap(18, 18, 18)
                .addComponent(pokemonImageLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pokemonPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Espacio vacío", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 14))); // NOI18N
        pokemonPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pokemonPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pokemonPanel5MouseClicked(evt);
            }
        });

        pokemonTitleLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pokemonPanel5Layout = new javax.swing.GroupLayout(pokemonPanel5);
        pokemonPanel5.setLayout(pokemonPanel5Layout);
        pokemonPanel5Layout.setHorizontalGroup(
            pokemonPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pokemonPanel5Layout.createSequentialGroup()
                .addComponent(pokemonTitleLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pokemonPanel5Layout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addComponent(pokemonImageLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        pokemonPanel5Layout.setVerticalGroup(
            pokemonPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pokemonPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pokemonTitleLabel5)
                .addGap(18, 18, 18)
                .addComponent(pokemonImageLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pokemonPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Espacio vacío", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 14))); // NOI18N
        pokemonPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pokemonPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pokemonPanel6MouseClicked(evt);
            }
        });

        pokemonTitleLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pokemonPanel6Layout = new javax.swing.GroupLayout(pokemonPanel6);
        pokemonPanel6.setLayout(pokemonPanel6Layout);
        pokemonPanel6Layout.setHorizontalGroup(
            pokemonPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pokemonPanel6Layout.createSequentialGroup()
                .addComponent(pokemonTitleLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pokemonPanel6Layout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addComponent(pokemonImageLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        pokemonPanel6Layout.setVerticalGroup(
            pokemonPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pokemonPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pokemonTitleLabel6)
                .addGap(18, 18, 18)
                .addComponent(pokemonImageLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pokemonPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Espacio vacío", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 14))); // NOI18N
        pokemonPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pokemonPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pokemonPanel7MouseClicked(evt);
            }
        });

        pokemonTitleLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pokemonPanel7Layout = new javax.swing.GroupLayout(pokemonPanel7);
        pokemonPanel7.setLayout(pokemonPanel7Layout);
        pokemonPanel7Layout.setHorizontalGroup(
            pokemonPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pokemonPanel7Layout.createSequentialGroup()
                .addComponent(pokemonTitleLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pokemonPanel7Layout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addComponent(pokemonImageLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        pokemonPanel7Layout.setVerticalGroup(
            pokemonPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pokemonPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pokemonTitleLabel7)
                .addGap(18, 18, 18)
                .addComponent(pokemonImageLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pokemonPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Espacio vacío", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 14))); // NOI18N
        pokemonPanel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pokemonPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pokemonPanel8MouseClicked(evt);
            }
        });

        pokemonTitleLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pokemonPanel8Layout = new javax.swing.GroupLayout(pokemonPanel8);
        pokemonPanel8.setLayout(pokemonPanel8Layout);
        pokemonPanel8Layout.setHorizontalGroup(
            pokemonPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pokemonPanel8Layout.createSequentialGroup()
                .addComponent(pokemonTitleLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pokemonPanel8Layout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addComponent(pokemonImageLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        pokemonPanel8Layout.setVerticalGroup(
            pokemonPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pokemonPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pokemonTitleLabel8)
                .addGap(18, 18, 18)
                .addComponent(pokemonImageLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pokemonPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Espacio vacío", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 14))); // NOI18N
        pokemonPanel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pokemonPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pokemonPanel9MouseClicked(evt);
            }
        });

        pokemonTitleLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pokemonPanel9Layout = new javax.swing.GroupLayout(pokemonPanel9);
        pokemonPanel9.setLayout(pokemonPanel9Layout);
        pokemonPanel9Layout.setHorizontalGroup(
            pokemonPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pokemonPanel9Layout.createSequentialGroup()
                .addComponent(pokemonTitleLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pokemonPanel9Layout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addComponent(pokemonImageLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        pokemonPanel9Layout.setVerticalGroup(
            pokemonPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pokemonPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pokemonTitleLabel9)
                .addGap(18, 18, 18)
                .addComponent(pokemonImageLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pokemonPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Espacio vacío", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 14))); // NOI18N
        pokemonPanel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pokemonPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pokemonPanel10MouseClicked(evt);
            }
        });

        pokemonTitleLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pokemonPanel10Layout = new javax.swing.GroupLayout(pokemonPanel10);
        pokemonPanel10.setLayout(pokemonPanel10Layout);
        pokemonPanel10Layout.setHorizontalGroup(
            pokemonPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pokemonPanel10Layout.createSequentialGroup()
                .addComponent(pokemonTitleLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pokemonPanel10Layout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addComponent(pokemonImageLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        pokemonPanel10Layout.setVerticalGroup(
            pokemonPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pokemonPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pokemonTitleLabel10)
                .addGap(18, 18, 18)
                .addComponent(pokemonImageLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout imageContainerPanelLayout = new javax.swing.GroupLayout(imageContainerPanel);
        imageContainerPanel.setLayout(imageContainerPanelLayout);
        imageContainerPanelLayout.setHorizontalGroup(
            imageContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imageContainerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(imageContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imageContainerPanelLayout.createSequentialGroup()
                        .addComponent(pokemonPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pokemonPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(imageContainerPanelLayout.createSequentialGroup()
                        .addComponent(pokemonPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pokemonPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(imageContainerPanelLayout.createSequentialGroup()
                        .addComponent(pokemonPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pokemonPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(imageContainerPanelLayout.createSequentialGroup()
                        .addComponent(pokemonPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pokemonPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(imageContainerPanelLayout.createSequentialGroup()
                        .addComponent(pokemonPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pokemonPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        imageContainerPanelLayout.setVerticalGroup(
            imageContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imageContainerPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(imageContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pokemonPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pokemonPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(imageContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pokemonPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pokemonPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(imageContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pokemonPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pokemonPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(imageContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pokemonPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pokemonPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(imageContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pokemonPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pokemonPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pokemonPanel1.getAccessibleContext().setAccessibleName("Pokemon");
        pokemonPanel1.getAccessibleContext().setAccessibleDescription("componente pokemon");

        jScrollPane1.setViewportView(imageContainerPanel);
        imageContainerPanel.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jLabel1)
                        .addGap(0, 218, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pokemonPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pokemonPanel2MouseClicked
       HelperClass.abrirPokemonFrame(this, juego, juego.jugador.mascotas[1]);
    }//GEN-LAST:event_pokemonPanel2MouseClicked

    private void pokemonPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pokemonPanel3MouseClicked
        HelperClass.abrirPokemonFrame(this, juego, juego.jugador.mascotas[2]);
    }//GEN-LAST:event_pokemonPanel3MouseClicked

    private void pokemonPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pokemonPanel4MouseClicked
        HelperClass.abrirPokemonFrame(this, juego, juego.jugador.mascotas[3]);
    }//GEN-LAST:event_pokemonPanel4MouseClicked

    private void pokemonPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pokemonPanel5MouseClicked
        HelperClass.abrirPokemonFrame(this, juego, juego.jugador.mascotas[4]);
    }//GEN-LAST:event_pokemonPanel5MouseClicked

    private void pokemonPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pokemonPanel6MouseClicked
        HelperClass.abrirPokemonFrame(this, juego, juego.jugador.mascotas[5]);
    }//GEN-LAST:event_pokemonPanel6MouseClicked

    private void pokemonPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pokemonPanel7MouseClicked
        HelperClass.abrirPokemonFrame(this, juego, juego.jugador.mascotas[6]);
    }//GEN-LAST:event_pokemonPanel7MouseClicked

    private void pokemonPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pokemonPanel8MouseClicked
        HelperClass.abrirPokemonFrame(this, juego, juego.jugador.mascotas[7]);
    }//GEN-LAST:event_pokemonPanel8MouseClicked

    private void pokemonPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pokemonPanel9MouseClicked
        HelperClass.abrirPokemonFrame(this, juego, juego.jugador.mascotas[8]);
    }//GEN-LAST:event_pokemonPanel9MouseClicked

    private void pokemonPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pokemonPanel10MouseClicked
        HelperClass.abrirPokemonFrame(this, juego, juego.jugador.mascotas[9]);
    }//GEN-LAST:event_pokemonPanel10MouseClicked

        private void pokemonPanel1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_pokemonPanel1MouseClicked
                HelperClass.abrirPokemonFrame(this, juego, juego.jugador.mascotas[0]);
        }// GEN-LAST:event_pokemonPanel1MouseClicked

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
                this.setVisible(false);
                parent.setVisible(true);
                // TODO add your handling code here:
        }// GEN-LAST:event_jButton1ActionPerformed

        /**
         * @param args the command line arguments
         */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel imageContainerPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pokemonImageLabel1;
    private javax.swing.JLabel pokemonImageLabel10;
    private javax.swing.JLabel pokemonImageLabel2;
    private javax.swing.JLabel pokemonImageLabel3;
    private javax.swing.JLabel pokemonImageLabel4;
    private javax.swing.JLabel pokemonImageLabel5;
    private javax.swing.JLabel pokemonImageLabel6;
    private javax.swing.JLabel pokemonImageLabel7;
    private javax.swing.JLabel pokemonImageLabel8;
    private javax.swing.JLabel pokemonImageLabel9;
    private javax.swing.JPanel pokemonPanel1;
    private javax.swing.JPanel pokemonPanel10;
    private javax.swing.JPanel pokemonPanel2;
    private javax.swing.JPanel pokemonPanel3;
    private javax.swing.JPanel pokemonPanel4;
    private javax.swing.JPanel pokemonPanel5;
    private javax.swing.JPanel pokemonPanel6;
    private javax.swing.JPanel pokemonPanel7;
    private javax.swing.JPanel pokemonPanel8;
    private javax.swing.JPanel pokemonPanel9;
    private javax.swing.JLabel pokemonTitleLabel1;
    private javax.swing.JLabel pokemonTitleLabel10;
    private javax.swing.JLabel pokemonTitleLabel2;
    private javax.swing.JLabel pokemonTitleLabel3;
    private javax.swing.JLabel pokemonTitleLabel4;
    private javax.swing.JLabel pokemonTitleLabel5;
    private javax.swing.JLabel pokemonTitleLabel6;
    private javax.swing.JLabel pokemonTitleLabel7;
    private javax.swing.JLabel pokemonTitleLabel8;
    private javax.swing.JLabel pokemonTitleLabel9;
    // End of variables declaration//GEN-END:variables
}
