/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.alejandrove.cuidarpokemon.frontend.mascota;

import com.alejandrove.cuidarpokemon.backend.Mascota;
import com.alejandrove.cuidarpokemon.backend.MotorJuego;
import com.alejandrove.cuidarpokemon.frontend.memoria.MemoriaFrame;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author aleja
 */
public class PasearFrame extends javax.swing.JFrame implements Runnable {

    public JFrame parent;
    MotorJuego juego;
    Mascota pokemon;

    /**
     * Creates new form PasearFrame
     */
    public PasearFrame(JFrame parent, MotorJuego juego, Mascota pokemon) {
        this.parent = parent;
        this.juego = juego;
        this.pokemon = pokemon;
        initComponents();
        regresarButton.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regresarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        regresarButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        regresarButton.setText("Regresar");
        regresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel1.setText("Estas paseando a tu mascota...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(85, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout.createSequentialGroup()
                                                        .addComponent(regresarButton)
                                                        .addContainerGap())
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout.createSequentialGroup()
                                                        .addComponent(jLabel1)
                                                        .addGap(72, 72, 72)))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(127, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(99, 99, 99)
                                .addComponent(regresarButton)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_regresarButtonActionPerformed
        this.setVisible(false);
        parent.setVisible(true);
    }// GEN-LAST:event_regresarButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton regresarButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        int pokemonEncontrados = (int) Math.floor(Math.random() * (1 - 0 + 1) + 0);
        for (int i = 0; i < pokemonEncontrados; i++) {
            try {
                Thread.sleep(500);
            } catch (Exception e) {
                System.out.println("Error en el sleep");
            }
            // memoriaFrame.setVisible(true);
            int nivelPokemonSalvaje;
            int probabilidadNivelPokemonSalvaje = (int) Math.floor(Math.random() * (100 - 0 + 1) + 0);
            if (probabilidadNivelPokemonSalvaje <= 34) {
                nivelPokemonSalvaje = (pokemon.getNivel() > 0) ? pokemon.getNivel() - 1 : 0;
            } else if (probabilidadNivelPokemonSalvaje <= 67) {
                nivelPokemonSalvaje = pokemon.getNivel() + 1;
            } else {
                nivelPokemonSalvaje = pokemon.getNivel() + 2;
            }

            MemoriaFrame memoriaFrame;
            if (nivelPokemonSalvaje == 7) {
                memoriaFrame = new MemoriaFrame(20, this);
            } else {

                memoriaFrame = new MemoriaFrame(4 + nivelPokemonSalvaje * 2, this);
            }
            JOptionPane.showMessageDialog(this,
                    "Tu pokemon ha encontrado a un pokemon salvaje de nivel " + nivelPokemonSalvaje
                            + ", preparate para luchar!",
                    "Pokemon Salvaje",
                    JOptionPane.INFORMATION_MESSAGE);
            memoriaFrame.setVisible(true);
            this.setVisible(false);
        }
        if (pokemonEncontrados == 0)
            mascotaPaseada(false);
    }

    public void mascotaPaseada(boolean gano) {
        JOptionPane.showMessageDialog(this, "Has paseado a tu mascota", "Mascota Paseada",
                JOptionPane.INFORMATION_MESSAGE);
        regresarButton.setEnabled(true);
        pokemon.pasear(gano);
    }
}
